export const HEALTH_SERVICE_GENERAL_FAIL: string =
  "HEALTH_SERVICE_GENERAL_FAIL";

export const CREATE_IO_JOB_GENERAL_FAIL: string = "CREATE_IO_JOB_GENERAL_FAIL";
export const CREATE_CPU_JOB_GENERAL_FAIL: string = "CREATE_CPU_JOB_GENERAL_FAIL";
export const GET_JOB_BY_ID_GENERAL_FAIL: string = "GET_JOB__BY_ID_GENERAL_FAIL";
export const GET_ALL_JOBS_GENERAL_FAIL: string = "GET_ALL_JOBS_GENERAL_FAIL";
export const DELETE_JOB_BY_ID_GENERAL_FAIL: string = "GET_ALL_JOBS_GENERAL_FAIL";